import type { HexId } from "./types";

export const ELEVATION_LINE_COUNT = 4;

// Generated by scripts/analyze-elevation.py from the four elevation-line
// vector objects in field.pdf. Each pair is an adjacent center-to-center move
// that crosses one of those lines.
const ELEVATION_EDGE_PAIRS = [
  ["0,0", "0,1"],
  ["0,0", "1,0"],
  ["0,1", "0,2"],
  ["0,1", "1,1"],
  ["0,2", "1,2"],
  ["0,3", "0,4"],
  ["0,4", "1,4"],
  ["0,4", "1,5"],
  ["0,5", "1,5"],
  ["0,5", "1,6"],
  ["0,6", "1,6"],
  ["0,6", "1,7"],
  ["0,7", "0,8"],
  ["0,7", "1,7"],
  ["0,7", "1,8"],
  ["1,0", "1,1"],
  ["1,1", "1,2"],
  ["1,1", "2,0"],
  ["1,2", "1,3"],
  ["1,2", "2,1"],
  ["1,3", "2,2"],
  ["2,0", "2,1"],
  ["2,0", "3,1"],
  ["2,1", "2,2"],
  ["2,2", "2,3"],
  ["2,2", "3,2"],
  ["2,3", "3,3"],
  ["2,3", "3,4"],
  ["2,4", "3,4"],
  ["2,4", "3,5"],
  ["2,5", "3,5"],
  ["2,5", "3,6"],
  ["2,6", "3,6"],
  ["2,6", "3,7"],
  ["2,7", "3,7"],
  ["2,7", "3,8"],
  ["2,8", "3,8"],
  ["2,8", "3,9"],
  ["2,9", "3,9"],
  ["2,9", "3,10"],
  ["3,0", "3,1"],
  ["3,0", "4,0"],
  ["3,1", "4,0"],
  ["3,1", "4,1"],
  ["3,2", "3,3"],
  ["3,2", "4,1"],
  ["3,2", "4,2"]
] as const satisfies readonly (readonly [HexId, HexId])[];

export function toEdgeId(first: HexId, second: HexId): string {
  return first < second ? `${first}|${second}` : `${second}|${first}`;
}

export const ELEVATION_EDGES = new Set(
  ELEVATION_EDGE_PAIRS.map(([first, second]) => toEdgeId(first, second))
);

// The Lobosch slope is represented by contour/elevation lines, not by a
// separate hill terrain type. These levels identify the higher side of those
// lines and are used only to determine whether an attack is uphill.
const ELEVATION_LEVEL_ONE_HEXES = new Set<HexId>([
  "0,0",
  "1,1",
  "2,1",
  "3,1",
  "3,2",
  "0,2",
  "0,3",
  "0,8",
  "0,9",
  "1,3",
  "1,4",
  "1,5",
  "1,6",
  "1,7",
  "1,8",
  "1,9",
  "1,10",
  "2,3",
  "2,4",
  "2,5",
  "2,6",
  "2,7",
  "2,8",
  "2,9"
]);

const ELEVATION_LEVEL_TWO_HEXES = new Set<HexId>([
  "0,4",
  "0,5",
  "0,6",
  "0,7",
  "1,0",
  "2,0",
  "3,0"
]);

export function elevationLevelFor(id: HexId): 0 | 1 | 2 {
  if (ELEVATION_LEVEL_TWO_HEXES.has(id)) return 2;
  return ELEVATION_LEVEL_ONE_HEXES.has(id) ? 1 : 0;
}

export function crossesElevationLine(first: HexId, second: HexId): boolean {
  return ELEVATION_EDGES.has(toEdgeId(first, second));
}
